### PR TITLE
fix build on gcc 4.8 (fixes #246)

### LINKED ISSUE #246: ftbfs on centos 7
Is there a specific gcc version required? Right now, current master fails to build from source on centos 7 (while it worked with the latest release 1.1.18)

```
libgearman/server_options.cc: In constructor 'gearman_server_options_st::gearman_server_options_st(gearman_universal_st&, const char*, size_t)':
libgearman/server_options.cc:69:23: error: invalid initialization of non-const reference of type 'gearman_universal_st&' from an rvalue of type '<brace-enclosed initializer list>'
   universal{universal_}
```

introduced with commit e3ea2b3.

```
$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)

$ cat /etc/redhat-release
CentOS Linux release 7.7.1908 (Core)
```

### PR DESCRIPTION
**Pull request by sni**
build fails with:

```
libgearman/server_options.cc: In constructor 'gearman_server_options_st::gearman_server_options_st(gearman_universal_st&, const char*, size_t)':
libgearman/server_options.cc:69:23: error: invalid initialization of non-const reference of type 'gearman_universal_st&' from an rvalue of type '<brace-enclosed initializer list>'
   universal{universal_}
```

Signed-off-by: Sven Nierlein <sven@nierlein.de>

### CODE REVIEW

**Comment by esabol** [comment]
Um, I already have a patch in progress for this, and all of my tests pass.

**Comment by sni** [comment]
sure, no problem, whatever works is fine for me :-)

**Comment by SpamapS** [comment]
We've landed a few fixes and things since the last release. Probably once this is done, we can make another release so folks can build on CentOS7 more easily.

**Comment by sni** [comment]
#248 is the better approach, please choose that one.
