### ISSUE TITLE
ftbfs on centos 7

### ISSUE THREAD

**Issue by sni** [gearman/gearmand#246]
Is there a specific gcc version required? Right now, current master fails to build from source on centos 7 (while it worked with the latest release 1.1.18)

```
libgearman/server_options.cc: In constructor 'gearman_server_options_st::gearman_server_options_st(gearman_universal_st&, const char*, size_t)':
libgearman/server_options.cc:69:23: error: invalid initialization of non-const reference of type 'gearman_universal_st&' from an rvalue of type '<brace-enclosed initializer list>'
   universal{universal_}
```

introduced with commit e3ea2b3.

```
$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)

$ cat /etc/redhat-release
CentOS Linux release 7.7.1908 (Core)
```

**Comment by esabol** [comment]
Our [Travis CI implementation](https://travis-ci.org/gearman/gearmand) tests with gcc 4.9. Does Travis CI support gcc 4.8? If so, we should add that as a target.

I have no objection to adding an `#ifdef` to support gcc 4.8.x, if the impact is small. Is that the only build error, @sni? Can you suggest a patch?

**Comment by esabol** [comment]
Answering my own questions, as usual. :)

Yes, Travis CI does support gcc 4.8, even though it's not in the example .travis.yml that's in the docs.

Changing `universal{universal_}` to `universal(universal_)` gets the code to compile.

A similar error in `libgearman-server/gearmand_thread.cc` on line 170 can be worked around by changing `_gearmand{gearmand_}` to `_gearmand(gearmand_)`.

With these changes, the tests seem to pass.

So what preprocessor conditional should we use here? Maybe the following?
```C
#if __GNUC__ == 4 && __GNUC_MINOR__ < 9
```
Or something that tests `_cplusplus` ?

@p-alik: Can you weigh in on this issue please?

**Comment by SpamapS** [comment]
seems legit. The fix should add 4.8 to the travis build

**Comment by esabol** [comment]
Done. This issue can be closed.
